"""Schema for ``balancesheet`` (tushare `pro.balancesheet`) — v1.

资产负债表:150+ 字段。PK: ``(ts_code, end_date, ann_date, f_ann_date)``。
"""
from quant_data.sources.base import FieldSpec, TableSchema

BALANCESHEET_V1 = TableSchema(
    table="balancesheet",
    version="v1",
    primary_key=["ts_code", "end_date", "ann_date", "f_ann_date"],
    fields={
        "ts_code": FieldSpec("ts_code", "string", "code", nullable=False),
        "ann_date": FieldSpec("ann_date", "date", "calendar", nullable=False),
        "f_ann_date": FieldSpec("f_ann_date", "date", "calendar", nullable=False),
        "end_date": FieldSpec("end_date", "date", "calendar", nullable=False),
        "report_type": FieldSpec("report_type", "string", "category", nullable=True),
        "total_share": FieldSpec("total_share", "float64", "share", nullable=True),
        "cap_rese": FieldSpec("cap_rese", "float64", "yuan", nullable=True),
        "undistr_porfit": FieldSpec("undistr_porfit", "float64", "yuan", nullable=True),
        "surplus_rese": FieldSpec("surplus_rese", "float64", "yuan", nullable=True),
        "special_rese": FieldSpec("special_rese", "float64", "yuan", nullable=True),
        "money_cap": FieldSpec("money_cap", "float64", "yuan", nullable=True),
        "trad_asset": FieldSpec("trad_asset", "float64", "yuan", nullable=True),
        "notes_receiv": FieldSpec("notes_receiv", "float64", "yuan", nullable=True),
        "accounts_receiv": FieldSpec("accounts_receiv", "float64", "yuan", nullable=True),
        "oth_receiv": FieldSpec("oth_receiv", "float64", "yuan", nullable=True),
        "prepayment": FieldSpec("prepayment", "float64", "yuan", nullable=True),
        "div_receiv": FieldSpec("div_receiv", "float64", "yuan", nullable=True),
        "int_receiv": FieldSpec("int_receiv", "float64", "yuan", nullable=True),
        "inventories": FieldSpec("inventories", "float64", "yuan", nullable=True),
        "amor_exp": FieldSpec("amor_exp", "float64", "yuan", nullable=True),
        "nca_within_1y": FieldSpec("nca_within_1y", "float64", "yuan", nullable=True),
        "sett_rsrv": FieldSpec("sett_rsrv", "float64", "yuan", nullable=True),
        "loanto_oth_bank_fi": FieldSpec("loanto_oth_bank_fi", "float64", "yuan", nullable=True),
        "premium_receiv": FieldSpec("premium_receiv", "float64", "yuan", nullable=True),
        "reinsur_receiv": FieldSpec("reinsur_receiv", "float64", "yuan", nullable=True),
        "reinsur_res_receiv": FieldSpec("reinsur_res_receiv", "float64", "yuan", nullable=True),
        "pur_resale_fa": FieldSpec("pur_resale_fa", "float64", "yuan", nullable=True),
        "oth_cur_assets": FieldSpec("oth_cur_assets", "float64", "yuan", nullable=True),
        "total_cur_assets": FieldSpec("total_cur_assets", "float64", "yuan", nullable=True),
        "fa_avail_for_sale": FieldSpec("fa_avail_for_sale", "float64", "yuan", nullable=True),
        "htm_invest": FieldSpec("htm_invest", "float64", "yuan", nullable=True),
        "lt_eqt_invest": FieldSpec("lt_eqt_invest", "float64", "yuan", nullable=True),
        "investment_real_estate": FieldSpec("investment_real_estate", "float64", "yuan", nullable=True),
        "time_deposits": FieldSpec("time_deposits", "float64", "yuan", nullable=True),
        "oth_assets": FieldSpec("oth_assets", "float64", "yuan", nullable=True),
        "lt_rec": FieldSpec("lt_rec", "float64", "yuan", nullable=True),
        "fix_assets": FieldSpec("fix_assets", "float64", "yuan", nullable=True),
        "cip": FieldSpec("cip", "float64", "yuan", nullable=True),
        "const_materials": FieldSpec("const_materials", "float64", "yuan", nullable=True),
        "fixed_assets_disp": FieldSpec("fixed_assets_disp", "float64", "yuan", nullable=True),
        "produc_bio_assets": FieldSpec("produc_bio_assets", "float64", "yuan", nullable=True),
        "oil_and_gas_assets": FieldSpec("oil_and_gas_assets", "float64", "yuan", nullable=True),
        "intan_assets": FieldSpec("intan_assets", "float64", "yuan", nullable=True),
        "r_and_d": FieldSpec("r_and_d", "float64", "yuan", nullable=True),
        "goodwill": FieldSpec("goodwill", "float64", "yuan", nullable=True),
        "lt_amor_exp": FieldSpec("lt_amor_exp", "float64", "yuan", nullable=True),
        "defer_tax_assets": FieldSpec("defer_tax_assets", "float64", "yuan", nullable=True),
        "decr_in_disbur": FieldSpec("decr_in_disbur", "float64", "yuan", nullable=True),
        "oth_nca": FieldSpec("oth_nca", "float64", "yuan", nullable=True),
        "total_nca": FieldSpec("total_nca", "float64", "yuan", nullable=True),
        "cash_reser_cb": FieldSpec("cash_reser_cb", "float64", "yuan", nullable=True),
        "depos_in_oth_fi": FieldSpec("depos_in_oth_fi", "float64", "yuan", nullable=True),
        "prec_metals": FieldSpec("prec_metals", "float64", "yuan", nullable=True),
        "deriv_assets": FieldSpec("deriv_assets", "float64", "yuan", nullable=True),
        "rr_reins_une_prem": FieldSpec("rr_reins_une_prem", "float64", "yuan", nullable=True),
        "rr_reins_outstd_cla": FieldSpec("rr_reins_outstd_cla", "float64", "yuan", nullable=True),
        "rr_reins_lins_liab": FieldSpec("rr_reins_lins_liab", "float64", "yuan", nullable=True),
        "rr_reins_lthins_liab": FieldSpec("rr_reins_lthins_liab", "float64", "yuan", nullable=True),
        "refund_depos": FieldSpec("refund_depos", "float64", "yuan", nullable=True),
        "ph_pledge_loans": FieldSpec("ph_pledge_loans", "float64", "yuan", nullable=True),
        "refund_cap_depos": FieldSpec("refund_cap_depos", "float64", "yuan", nullable=True),
        "indep_acct_assets": FieldSpec("indep_acct_assets", "float64", "yuan", nullable=True),
        "client_depos": FieldSpec("client_depos", "float64", "yuan", nullable=True),
        "client_prov": FieldSpec("client_prov", "float64", "yuan", nullable=True),
        "transac_seat_fee": FieldSpec("transac_seat_fee", "float64", "yuan", nullable=True),
        "invest_as_receiv": FieldSpec("invest_as_receiv", "float64", "yuan", nullable=True),
        "total_assets": FieldSpec("total_assets", "float64", "yuan", nullable=True,
                                  description="资产总计"),
        "lt_borr": FieldSpec("lt_borr", "float64", "yuan", nullable=True),
        "st_borr": FieldSpec("st_borr", "float64", "yuan", nullable=True),
        "cb_borr": FieldSpec("cb_borr", "float64", "yuan", nullable=True),
        "depos_ib_deposits": FieldSpec("depos_ib_deposits", "float64", "yuan", nullable=True),
        "loan_oth_bank": FieldSpec("loan_oth_bank", "float64", "yuan", nullable=True),
        "trading_fl": FieldSpec("trading_fl", "float64", "yuan", nullable=True),
        "notes_payable": FieldSpec("notes_payable", "float64", "yuan", nullable=True),
        "acct_payable": FieldSpec("acct_payable", "float64", "yuan", nullable=True),
        "adv_receipts": FieldSpec("adv_receipts", "float64", "yuan", nullable=True),
        "sold_for_repur_fa": FieldSpec("sold_for_repur_fa", "float64", "yuan", nullable=True),
        "comm_payable": FieldSpec("comm_payable", "float64", "yuan", nullable=True),
        "payroll_payable": FieldSpec("payroll_payable", "float64", "yuan", nullable=True),
        "taxes_payable": FieldSpec("taxes_payable", "float64", "yuan", nullable=True),
        "int_payable": FieldSpec("int_payable", "float64", "yuan", nullable=True),
        "div_payable": FieldSpec("div_payable", "float64", "yuan", nullable=True),
        "oth_payable": FieldSpec("oth_payable", "float64", "yuan", nullable=True),
        "acc_exp": FieldSpec("acc_exp", "float64", "yuan", nullable=True),
        "deferred_inc": FieldSpec("deferred_inc", "float64", "yuan", nullable=True),
        "st_bonds_payable": FieldSpec("st_bonds_payable", "float64", "yuan", nullable=True),
        "payable_to_reinsurer": FieldSpec("payable_to_reinsurer", "float64", "yuan", nullable=True),
        "rsrv_insur_cont": FieldSpec("rsrv_insur_cont", "float64", "yuan", nullable=True),
        "acting_trading_sec": FieldSpec("acting_trading_sec", "float64", "yuan", nullable=True),
        "acting_uw_sec": FieldSpec("acting_uw_sec", "float64", "yuan", nullable=True),
        "non_cur_liab_due_1y": FieldSpec("non_cur_liab_due_1y", "float64", "yuan", nullable=True),
        "oth_cur_liab": FieldSpec("oth_cur_liab", "float64", "yuan", nullable=True),
        "total_cur_liab": FieldSpec("total_cur_liab", "float64", "yuan", nullable=True),
        "bond_payable": FieldSpec("bond_payable", "float64", "yuan", nullable=True),
        "lt_payable": FieldSpec("lt_payable", "float64", "yuan", nullable=True),
        "specific_payables": FieldSpec("specific_payables", "float64", "yuan", nullable=True),
        "estimated_liab": FieldSpec("estimated_liab", "float64", "yuan", nullable=True),
        "defer_tax_liab": FieldSpec("defer_tax_liab", "float64", "yuan", nullable=True),
        "defer_inc_non_cur_liab": FieldSpec("defer_inc_non_cur_liab", "float64", "yuan", nullable=True),
        "oth_ncl": FieldSpec("oth_ncl", "float64", "yuan", nullable=True),
        "total_ncl": FieldSpec("total_ncl", "float64", "yuan", nullable=True),
        "depos_oth_bfi": FieldSpec("depos_oth_bfi", "float64", "yuan", nullable=True),
        "deriv_liab": FieldSpec("deriv_liab", "float64", "yuan", nullable=True),
        "depos": FieldSpec("depos", "float64", "yuan", nullable=True),
        "agency_business_liab": FieldSpec("agency_business_liab", "float64", "yuan", nullable=True),
        "oth_liab": FieldSpec("oth_liab", "float64", "yuan", nullable=True),
        "prem_receiv_adva": FieldSpec("prem_receiv_adva", "float64", "yuan", nullable=True),
        "depos_received": FieldSpec("depos_received", "float64", "yuan", nullable=True),
        "ph_invest": FieldSpec("ph_invest", "float64", "yuan", nullable=True),
        "reser_une_prem": FieldSpec("reser_une_prem", "float64", "yuan", nullable=True),
        "reser_outstd_claims": FieldSpec("reser_outstd_claims", "float64", "yuan", nullable=True),
        "reser_lins_liab": FieldSpec("reser_lins_liab", "float64", "yuan", nullable=True),
        "reser_lthins_liab": FieldSpec("reser_lthins_liab", "float64", "yuan", nullable=True),
        "indept_acc_liab": FieldSpec("indept_acc_liab", "float64", "yuan", nullable=True),
        "pledge_borr": FieldSpec("pledge_borr", "float64", "yuan", nullable=True),
        "indem_payable": FieldSpec("indem_payable", "float64", "yuan", nullable=True),
        "total_liab": FieldSpec("total_liab", "float64", "yuan", nullable=True,
                                description="负债合计"),
        "treasury_share": FieldSpec("treasury_share", "float64", "yuan", nullable=True),
        "ordin_risk_reser": FieldSpec("ordin_risk_reser", "float64", "yuan", nullable=True),
        "forex_differ": FieldSpec("forex_differ", "float64", "yuan", nullable=True),
        "invest_loss_unconf": FieldSpec("invest_loss_unconf", "float64", "yuan", nullable=True),
        "minority_int": FieldSpec("minority_int", "float64", "yuan", nullable=True),
        "total_hldr_eqy_exc_min_int": FieldSpec("total_hldr_eqy_exc_min_int", "float64", "yuan", nullable=True),
        "total_hldr_eqy_inc_min_int": FieldSpec("total_hldr_eqy_inc_min_int", "float64", "yuan", nullable=True),
        "total_liab_hldr_eqy": FieldSpec("total_liab_hldr_eqy", "float64", "yuan", nullable=True),
        "lt_payroll_payable": FieldSpec("lt_payroll_payable", "float64", "yuan", nullable=True),
        "oth_comp_income": FieldSpec("oth_comp_income", "float64", "yuan", nullable=True),
        "oth_eqt_tools": FieldSpec("oth_eqt_tools", "float64", "yuan", nullable=True),
        "oth_eqt_tools_p_shr": FieldSpec("oth_eqt_tools_p_shr", "float64", "yuan", nullable=True),
        "lending_funds": FieldSpec("lending_funds", "float64", "yuan", nullable=True),
        "acc_receivable": FieldSpec("acc_receivable", "float64", "yuan", nullable=True),
        "st_fin_payable": FieldSpec("st_fin_payable", "float64", "yuan", nullable=True),
        "payables": FieldSpec("payables", "float64", "yuan", nullable=True),
        "hfs_assets": FieldSpec("hfs_assets", "float64", "yuan", nullable=True),
        "hfs_sales": FieldSpec("hfs_sales", "float64", "yuan", nullable=True),
        "update_flag": FieldSpec("update_flag", "string", "flag", nullable=True),
    },
    source_mapping={
        "tushare": {f: f for f in [
            "ts_code", "ann_date", "f_ann_date", "end_date", "report_type",
            "total_share", "cap_rese", "undistr_porfit", "surplus_rese",
            "special_rese", "money_cap", "trad_asset", "notes_receiv",
            "accounts_receiv", "oth_receiv", "prepayment", "div_receiv",
            "int_receiv", "inventories", "amor_exp", "nca_within_1y",
            "sett_rsrv", "loanto_oth_bank_fi", "premium_receiv",
            "reinsur_receiv", "reinsur_res_receiv", "pur_resale_fa",
            "oth_cur_assets", "total_cur_assets", "fa_avail_for_sale",
            "htm_invest", "lt_eqt_invest", "investment_real_estate",
            "time_deposits", "oth_assets", "lt_rec", "fix_assets", "cip",
            "const_materials", "fixed_assets_disp", "produc_bio_assets",
            "oil_and_gas_assets", "intan_assets", "r_and_d", "goodwill",
            "lt_amor_exp", "defer_tax_assets", "decr_in_disbur", "oth_nca",
            "total_nca", "cash_reser_cb", "depos_in_oth_fi", "prec_metals",
            "deriv_assets", "rr_reins_une_prem", "rr_reins_outstd_cla",
            "rr_reins_lins_liab", "rr_reins_lthins_liab", "refund_depos",
            "ph_pledge_loans", "refund_cap_depos", "indep_acct_assets",
            "client_depos", "client_prov", "transac_seat_fee",
            "invest_as_receiv", "total_assets", "lt_borr", "st_borr",
            "cb_borr", "depos_ib_deposits", "loan_oth_bank", "trading_fl",
            "notes_payable", "acct_payable", "adv_receipts",
            "sold_for_repur_fa", "comm_payable", "payroll_payable",
            "taxes_payable", "int_payable", "div_payable", "oth_payable",
            "acc_exp", "deferred_inc", "st_bonds_payable",
            "payable_to_reinsurer", "rsrv_insur_cont", "acting_trading_sec",
            "acting_uw_sec", "non_cur_liab_due_1y", "oth_cur_liab",
            "total_cur_liab", "bond_payable", "lt_payable",
            "specific_payables", "estimated_liab", "defer_tax_liab",
            "defer_inc_non_cur_liab", "oth_ncl", "total_ncl",
            "depos_oth_bfi", "deriv_liab", "depos", "agency_business_liab",
            "oth_liab", "prem_receiv_adva", "depos_received", "ph_invest",
            "reser_une_prem", "reser_outstd_claims", "reser_lins_liab",
            "reser_lthins_liab", "indept_acc_liab", "pledge_borr",
            "indem_payable", "total_liab", "treasury_share",
            "ordin_risk_reser", "forex_differ", "invest_loss_unconf",
            "minority_int", "total_hldr_eqy_exc_min_int",
            "total_hldr_eqy_inc_min_int", "total_liab_hldr_eqy",
            "lt_payroll_payable", "oth_comp_income", "oth_eqt_tools",
            "oth_eqt_tools_p_shr", "lending_funds", "acc_receivable",
            "st_fin_payable", "payables", "hfs_assets", "hfs_sales",
            "update_flag",
        ]},
    },
)
