"""Schema for ``cashflow`` (tushare `pro.cashflow`) — v1.

现金流量表:95+ 字段。PK: ``(ts_code, end_date, ann_date, f_ann_date)``。
"""
from quant_data.sources.base import FieldSpec, TableSchema

CASHFLOW_V1 = TableSchema(
    table="cashflow",
    version="v1",
    primary_key=["ts_code", "end_date", "ann_date", "f_ann_date"],
    fields={
        "ts_code": FieldSpec("ts_code", "string", "code", nullable=False),
        "ann_date": FieldSpec("ann_date", "date", "calendar", nullable=False),
        "f_ann_date": FieldSpec("f_ann_date", "date", "calendar", nullable=False),
        "end_date": FieldSpec("end_date", "date", "calendar", nullable=False),
        "report_type": FieldSpec("report_type", "string", "category", nullable=True),
        "net_profit": FieldSpec("net_profit", "float64", "yuan", nullable=True),
        "finan_exp": FieldSpec("finan_exp", "float64", "yuan", nullable=True),
        "c_fr_sale_sg": FieldSpec("c_fr_sale_sg", "float64", "yuan", nullable=True),
        "recp_tax_rdfs": FieldSpec("recp_tax_rdfs", "float64", "yuan", nullable=True),
        "n_depos_incr_fi": FieldSpec("n_depos_incr_fi", "float64", "yuan", nullable=True),
        "n_incr_loans_cb": FieldSpec("n_incr_loans_cb", "float64", "yuan", nullable=True),
        "n_inc_borr_oth_fi": FieldSpec("n_inc_borr_oth_fi", "float64", "yuan", nullable=True),
        "prem_fr_orig_contr": FieldSpec("prem_fr_orig_contr", "float64", "yuan", nullable=True),
        "n_incr_insured_dep": FieldSpec("n_incr_insured_dep", "float64", "yuan", nullable=True),
        "n_reinsur_prem": FieldSpec("n_reinsur_prem", "float64", "yuan", nullable=True),
        "n_incr_disp_tfa": FieldSpec("n_incr_disp_tfa", "float64", "yuan", nullable=True),
        "ifc_cash_incr": FieldSpec("ifc_cash_incr", "float64", "yuan", nullable=True),
        "oth_cash_in_oper": FieldSpec("oth_cash_in_oper", "float64", "yuan", nullable=True),
        "st_cash_out_oper": FieldSpec("st_cash_out_oper", "float64", "yuan", nullable=True),
        "c_paid_goods_s": FieldSpec("c_paid_goods_s", "float64", "yuan", nullable=True),
        "c_paid_to_for_empl": FieldSpec("c_paid_to_for_empl", "float64", "yuan", nullable=True),
        "c_paid_for_taxes": FieldSpec("c_paid_for_taxes", "float64", "yuan", nullable=True),
        "n_incr_clt_loan_adv": FieldSpec("n_incr_clt_loan_adv", "float64", "yuan", nullable=True),
        "n_incr_dep_cbob": FieldSpec("n_incr_dep_cbob", "float64", "yuan", nullable=True),
        "c_pay_claims_orig_inco": FieldSpec("c_pay_claims_orig_inco", "float64", "yuan", nullable=True),
        "pay_handling_chrg": FieldSpec("pay_handling_chrg", "float64", "yuan", nullable=True),
        "pay_comm_insur_plcy": FieldSpec("pay_comm_insur_plcy", "float64", "yuan", nullable=True),
        "oth_cash_pay_oper": FieldSpec("oth_cash_pay_oper", "float64", "yuan", nullable=True),
        "st_cash_in_oper": FieldSpec("st_cash_in_oper", "float64", "yuan", nullable=True),
        "net_cash_flows_oper": FieldSpec("net_cash_flows_oper", "float64", "yuan", nullable=True,
                                         description="经营活动现金流净额"),
        "cash_recp_disp_withdrwl_invest": FieldSpec("cash_recp_disp_withdrwl_invest", "float64", "yuan", nullable=True),
        "cash_recp_return_invest": FieldSpec("cash_recp_return_invest", "float64", "yuan", nullable=True),
        "n_cash_flows_fund": FieldSpec("n_cash_flows_fund", "float64", "yuan", nullable=True),
        "cash_recp_cap_contrib": FieldSpec("cash_recp_cap_contrib", "float64", "yuan", nullable=True),
        "cash_inflow_oth_invest": FieldSpec("cash_inflow_oth_invest", "float64", "yuan", nullable=True),
        "cash_recp_disp_filt_assets": FieldSpec("cash_recp_disp_filt_assets", "float64", "yuan", nullable=True),
        "cash_recp_disp_subs": FieldSpec("cash_recp_disp_subs", "float64", "yuan", nullable=True),
        "cash_recp_disp_oth_op": FieldSpec("cash_recp_disp_oth_op", "float64", "yuan", nullable=True),
        "stot_inflows_inv_act": FieldSpec("stot_inflows_inv_act", "float64", "yuan", nullable=True),
        "c_pay_acq_const_filt_assets": FieldSpec("c_pay_acq_const_filt_assets", "float64", "yuan", nullable=True),
        "c_paid_invest": FieldSpec("c_paid_invest", "float64", "yuan", nullable=True),
        "c_paid_disp_filt_assets": FieldSpec("c_paid_disp_filt_assets", "float64", "yuan", nullable=True),
        "c_pay_subs": FieldSpec("c_pay_subs", "float64", "yuan", nullable=True),
        "c_pay_oth_invest": FieldSpec("c_pay_oth_invest", "float64", "yuan", nullable=True),
        "stot_out_inv_act": FieldSpec("stot_out_inv_act", "float64", "yuan", nullable=True),
        "net_cash_flows_inv_act": FieldSpec("net_cash_flows_inv_act", "float64", "yuan", nullable=True,
                                            description="投资活动现金流净额"),
        "cash_recp_borrow": FieldSpec("cash_recp_borrow", "float64", "yuan", nullable=True),
        "cash_recp_issue_bonds": FieldSpec("cash_recp_issue_bonds", "float64", "yuan", nullable=True),
        "cash_recp_oth_fin_act": FieldSpec("cash_recp_oth_fin_act", "float64", "yuan", nullable=True),
        "stot_cash_in_fin_act": FieldSpec("stot_cash_in_fin_act", "float64", "yuan", nullable=True),
        "c_prepay_amt_borr": FieldSpec("c_prepay_amt_borr", "float64", "yuan", nullable=True),
        "c_pay_dist_dpcp_int_exp": FieldSpec("c_pay_dist_dpcp_int_exp", "float64", "yuan", nullable=True),
        "c_pay_dividend": FieldSpec("c_pay_dividend", "float64", "yuan", nullable=True),
        "oth_cash_pay_fin_act": FieldSpec("oth_cash_pay_fin_act", "float64", "yuan", nullable=True),
        "stot_cashout_fin_act": FieldSpec("stot_cashout_fin_act", "float64", "yuan", nullable=True),
        "net_cash_flows_fin_act": FieldSpec("net_cash_flows_fin_act", "float64", "yuan", nullable=True,
                                            description="筹资活动现金流净额"),
        "eff_fx_flu_cash": FieldSpec("eff_fx_flu_cash", "float64", "yuan", nullable=True),
        "n_incr_cash_cash_equ": FieldSpec("n_incr_cash_cash_equ", "float64", "yuan", nullable=True,
                                          description="现金净增加额"),
        "c_cash_equ_beg_period": FieldSpec("c_cash_equ_beg_period", "float64", "yuan", nullable=True),
        "c_cash_equ_end_period": FieldSpec("c_cash_equ_end_period", "float64", "yuan", nullable=True),
        "free_cashflow": FieldSpec("free_cashflow", "float64", "yuan", nullable=True,
                                   description="自由现金流"),
        "im_net_cashflow_oper_act": FieldSpec("im_net_cashflow_oper_act", "float64", "yuan", nullable=True),
        "net_dism_capital_add": FieldSpec("net_dism_capital_add", "float64", "yuan", nullable=True),
        "net_cash_rece_sec": FieldSpec("net_cash_rece_sec", "float64", "yuan", nullable=True),
        "credit_impa_loss": FieldSpec("credit_impa_loss", "float64", "yuan", nullable=True),
        "use_right_asset_dep": FieldSpec("use_right_asset_dep", "float64", "yuan", nullable=True),
        "oth_loss_asset": FieldSpec("oth_loss_asset", "float64", "yuan", nullable=True),
        "end_bal_cash": FieldSpec("end_bal_cash", "float64", "yuan", nullable=True),
        "beg_bal_cash": FieldSpec("beg_bal_cash", "float64", "yuan", nullable=True),
        "end_bal_cash_equ": FieldSpec("end_bal_cash_equ", "float64", "yuan", nullable=True),
        "begin_bal_cash_equ": FieldSpec("begin_bal_cash_equ", "float64", "yuan", nullable=True),
        "update_flag": FieldSpec("update_flag", "string", "flag", nullable=True),
    },
    source_mapping={
        "tushare": {f: f for f in [
            "ts_code", "ann_date", "f_ann_date", "end_date", "report_type",
            "net_profit", "finan_exp", "c_fr_sale_sg", "recp_tax_rdfs",
            "n_depos_incr_fi", "n_incr_loans_cb", "n_inc_borr_oth_fi",
            "prem_fr_orig_contr", "n_incr_insured_dep", "n_reinsur_prem",
            "n_incr_disp_tfa", "ifc_cash_incr", "oth_cash_in_oper",
            "st_cash_out_oper", "c_paid_goods_s", "c_paid_to_for_empl",
            "c_paid_for_taxes", "n_incr_clt_loan_adv", "n_incr_dep_cbob",
            "c_pay_claims_orig_inco", "pay_handling_chrg", "pay_comm_insur_plcy",
            "oth_cash_pay_oper", "st_cash_in_oper", "net_cash_flows_oper",
            "cash_recp_disp_withdrwl_invest", "cash_recp_return_invest",
            "n_cash_flows_fund", "cash_recp_cap_contrib", "cash_inflow_oth_invest",
            "cash_recp_disp_filt_assets", "cash_recp_disp_subs",
            "cash_recp_disp_oth_op", "stot_inflows_inv_act",
            "c_pay_acq_const_filt_assets", "c_paid_invest",
            "c_paid_disp_filt_assets", "c_pay_subs", "c_pay_oth_invest",
            "stot_out_inv_act", "net_cash_flows_inv_act", "cash_recp_borrow",
            "cash_recp_issue_bonds", "cash_recp_oth_fin_act",
            "stot_cash_in_fin_act", "c_prepay_amt_borr",
            "c_pay_dist_dpcp_int_exp", "c_pay_dividend",
            "oth_cash_pay_fin_act", "stot_cashout_fin_act",
            "net_cash_flows_fin_act", "eff_fx_flu_cash", "n_incr_cash_cash_equ",
            "c_cash_equ_beg_period", "c_cash_equ_end_period", "free_cashflow",
            "im_net_cashflow_oper_act", "net_dism_capital_add",
            "net_cash_rece_sec", "credit_impa_loss", "use_right_asset_dep",
            "oth_loss_asset", "end_bal_cash", "beg_bal_cash",
            "end_bal_cash_equ", "begin_bal_cash_equ", "update_flag",
        ]},
    },
)
