"""Schema for ``fina_indicator`` (tushare `pro.fina_indicator`) — v1.

财务关键指标:ROE / ROA / 毛利率 / 净利率 / EPS / BPS / 增速。80+ 字段。
PK: ``(ts_code, end_date, ann_date)`` —— end_date = 报告期;ann_date = 公告日。
"""
from quant_data.sources.base import FieldSpec, TableSchema

FINA_INDICATOR_V1 = TableSchema(
    table="fina_indicator",
    version="v1",
    primary_key=["ts_code", "end_date", "ann_date"],
    fields={
        "ts_code": FieldSpec("ts_code", "string", "code", nullable=False),
        "end_date": FieldSpec("end_date", "date", "calendar", nullable=False,
                              description="报告期"),
        "ann_date": FieldSpec("ann_date", "date", "calendar", nullable=False,
                              description="公告日 (f_ann_date 字段 = 实际公告)"),
        "f_ann_date": FieldSpec("f_ann_date", "date", "calendar", nullable=True,
                                description="实际公告日"),
        "eps": FieldSpec("eps", "float64", "yuan", nullable=True,
                         description="基本每股收益"),
        "dt_eps": FieldSpec("dt_eps", "float64", "yuan", nullable=True,
                            description="扣非每股收益"),
        "total_revenue_ps": FieldSpec("total_revenue_ps", "float64", "yuan", nullable=True,
                                      description="每股营业总收入"),
        "revenue_ps": FieldSpec("revenue_ps", "float64", "yuan", nullable=True,
                                description="每股营业收入"),
        "capital_rese_ps": FieldSpec("capital_rese_ps", "float64", "yuan", nullable=True),
        "surplus_rese_ps": FieldSpec("surplus_rese_ps", "float64", "yuan", nullable=True),
        "undist_profit_ps": FieldSpec("undist_profit_ps", "float64", "yuan", nullable=True),
        "extra_item": FieldSpec("extra_item", "float64", "yuan", nullable=True),
        "profit_dedt": FieldSpec("profit_dedt", "float64", "yuan", nullable=True,
                                 description="扣非净利润"),
        "gross_margin": FieldSpec("gross_margin", "float64", "pct", nullable=True,
                                  description="毛利率"),
        "current_ratio": FieldSpec("current_ratio", "float64", "ratio", nullable=True),
        "quick_ratio": FieldSpec("quick_ratio", "float64", "ratio", nullable=True),
        "cash_ratio": FieldSpec("cash_ratio", "float64", "ratio", nullable=True),
        "ar_turn": FieldSpec("ar_turn", "float64", "ratio", nullable=True,
                             description="应收账款周转率"),
        "ca_turn": FieldSpec("ca_turn", "float64", "ratio", nullable=True,
                             description="流动资产周转率"),
        "fa_turn": FieldSpec("fa_turn", "float64", "ratio", nullable=True,
                             description="固定资产周转率"),
        "assets_turn": FieldSpec("assets_turn", "float64", "ratio", nullable=True,
                                 description="总资产周转率"),
        "op_income": FieldSpec("op_income", "float64", "yuan", nullable=True,
                               description="经营活动净收益"),
        "ebit": FieldSpec("ebit", "float64", "yuan", nullable=True,
                          description="息税前利润"),
        "ebitda": FieldSpec("ebitda", "float64", "yuan", nullable=True,
                            description="息税折旧摊销前利润"),
        "netprofit_margin": FieldSpec("netprofit_margin", "float64", "pct", nullable=True,
                                      description="净利率"),
        "grossprofit_margin": FieldSpec("grossprofit_margin", "float64", "pct", nullable=True),
        "cogs_of_sales": FieldSpec("cogs_of_sales", "float64", "pct", nullable=True),
        "expense_of_sales": FieldSpec("expense_of_sales", "float64", "pct", nullable=True),
        "profit_to_gr": FieldSpec("profit_to_gr", "float64", "pct", nullable=True),
        "saleexp_to_gr": FieldSpec("saleexp_to_gr", "float64", "pct", nullable=True),
        "adminexp_to_gr": FieldSpec("adminexp_to_gr", "float64", "pct", nullable=True),
        "finaexp_to_gr": FieldSpec("finaexp_to_gr", "float64", "pct", nullable=True),
        "impai_ttm": FieldSpec("impai_ttm", "float64", "yuan", nullable=True),
        "gc_of_gr": FieldSpec("gc_of_gr", "float64", "pct", nullable=True),
        "op_of_gr": FieldSpec("op_of_gr", "float64", "pct", nullable=True),
        "ebit_of_gr": FieldSpec("ebit_of_gr", "float64", "pct", nullable=True),
        "roe": FieldSpec("roe", "float64", "pct", nullable=True,
                         description="ROE 净资产收益率"),
        "roe_waa": FieldSpec("roe_waa", "float64", "pct", nullable=True,
                             description="ROE 加权"),
        "roe_dt": FieldSpec("roe_dt", "float64", "pct", nullable=True,
                            description="ROE 扣非"),
        "roa": FieldSpec("roa", "float64", "pct", nullable=True,
                         description="ROA 总资产收益率"),
        "npta": FieldSpec("npta", "float64", "pct", nullable=True,
                          description="净利润 / 总资产"),
        "roic": FieldSpec("roic", "float64", "pct", nullable=True,
                          description="ROIC 投入资本回报率"),
        "roe_yearly": FieldSpec("roe_yearly", "float64", "pct", nullable=True),
        "roa2_yearly": FieldSpec("roa2_yearly", "float64", "pct", nullable=True),
        "debt_to_assets": FieldSpec("debt_to_assets", "float64", "pct", nullable=True,
                                    description="资产负债率"),
        "assets_to_eqt": FieldSpec("assets_to_eqt", "float64", "ratio", nullable=True),
        "dp_assets_to_eqt": FieldSpec("dp_assets_to_eqt", "float64", "ratio", nullable=True),
        "ca_to_assets": FieldSpec("ca_to_assets", "float64", "pct", nullable=True),
        "nca_to_assets": FieldSpec("nca_to_assets", "float64", "pct", nullable=True),
        "tbassets_to_totalassets": FieldSpec("tbassets_to_totalassets", "float64", "pct", nullable=True),
        "int_to_talcap": FieldSpec("int_to_talcap", "float64", "pct", nullable=True),
        "eqt_to_talcap": FieldSpec("eqt_to_talcap", "float64", "pct", nullable=True),
        "currentdebt_to_debt": FieldSpec("currentdebt_to_debt", "float64", "pct", nullable=True),
        "longdeb_to_debt": FieldSpec("longdeb_to_debt", "float64", "pct", nullable=True),
        "ocf_to_shortdebt": FieldSpec("ocf_to_shortdebt", "float64", "ratio", nullable=True),
        "debt_to_eqt": FieldSpec("debt_to_eqt", "float64", "ratio", nullable=True,
                                 description="产权比率"),
        "eqt_to_debt": FieldSpec("eqt_to_debt", "float64", "ratio", nullable=True),
        "equity_yoy": FieldSpec("equity_yoy", "float64", "pct", nullable=True,
                                description="净资产同比"),
        "rd_exp": FieldSpec("rd_exp", "float64", "yuan", nullable=True,
                            description="研发费用"),
        "update_flag": FieldSpec("update_flag", "string", "flag", nullable=True,
                                 description="1=正式 0=待审"),
    },
    source_mapping={
        "tushare": {f: f for f in [
            "ts_code", "end_date", "ann_date", "f_ann_date",
            "eps", "dt_eps", "total_revenue_ps", "revenue_ps",
            "capital_rese_ps", "surplus_rese_ps", "undist_profit_ps",
            "extra_item", "profit_dedt", "gross_margin",
            "current_ratio", "quick_ratio", "cash_ratio",
            "ar_turn", "ca_turn", "fa_turn", "assets_turn",
            "op_income", "ebit", "ebitda", "netprofit_margin",
            "grossprofit_margin", "cogs_of_sales", "expense_of_sales",
            "profit_to_gr", "saleexp_to_gr", "adminexp_to_gr", "finaexp_to_gr",
            "impai_ttm", "gc_of_gr", "op_of_gr", "ebit_of_gr",
            "roe", "roe_waa", "roe_dt", "roa", "npta", "roic",
            "roe_yearly", "roa2_yearly", "debt_to_assets",
            "assets_to_eqt", "dp_assets_to_eqt", "ca_to_assets",
            "nca_to_assets", "tbassets_to_totalassets", "int_to_talcap",
            "eqt_to_talcap", "currentdebt_to_debt", "longdeb_to_debt",
            "ocf_to_shortdebt", "debt_to_eqt", "eqt_to_debt",
            "equity_yoy", "rd_exp", "update_flag",
        ]},
    },
)
