"""Schema for ``income`` (tushare `pro.income`) — v1.

利润表:85+ 字段。PK: ``(ts_code, end_date, ann_date, f_ann_date)``。
"""
from quant_data.sources.base import FieldSpec, TableSchema

INCOME_V1 = TableSchema(
    table="income",
    version="v1",
    primary_key=["ts_code", "end_date", "ann_date", "f_ann_date"],
    fields={
        "ts_code": FieldSpec("ts_code", "string", "code", nullable=False),
        "ann_date": FieldSpec("ann_date", "date", "calendar", nullable=False,
                              description="公告日"),
        "f_ann_date": FieldSpec("f_ann_date", "date", "calendar", nullable=False,
                                description="实际公告日"),
        "end_date": FieldSpec("end_date", "date", "calendar", nullable=False,
                              description="报告期"),
        "report_type": FieldSpec("report_type", "string", "category", nullable=True,
                                 description="1=合并 2=母公司"),
        "basic_eps": FieldSpec("basic_eps", "float64", "yuan", nullable=True),
        "diluted_eps": FieldSpec("diluted_eps", "float64", "yuan", nullable=True),
        "total_revenue": FieldSpec("total_revenue", "float64", "yuan", nullable=True),
        "revenue": FieldSpec("revenue", "float64", "yuan", nullable=True),
        "int_income": FieldSpec("int_income", "float64", "yuan", nullable=True),
        "prem_earned": FieldSpec("prem_earned", "float64", "yuan", nullable=True),
        "comm_income": FieldSpec("comm_income", "float64", "yuan", nullable=True),
        "n_commis_income": FieldSpec("n_commis_income", "float64", "yuan", nullable=True),
        "n_oth_income": FieldSpec("n_oth_income", "float64", "yuan", nullable=True),
        "n_oth_b_income": FieldSpec("n_oth_b_income", "float64", "yuan", nullable=True),
        "prem_income": FieldSpec("prem_income", "float64", "yuan", nullable=True),
        "out_prem": FieldSpec("out_prem", "float64", "yuan", nullable=True),
        "une_prem_reser": FieldSpec("une_prem_reser", "float64", "yuan", nullable=True),
        "reins_income": FieldSpec("reins_income", "float64", "yuan", nullable=True),
        "n_sec_tb_income": FieldSpec("n_sec_tb_income", "float64", "yuan", nullable=True),
        "n_sec_uw_income": FieldSpec("n_sec_uw_income", "float64", "yuan", nullable=True),
        "n_asset_mg_income": FieldSpec("n_asset_mg_income", "float64", "yuan", nullable=True),
        "oth_b_income": FieldSpec("oth_b_income", "float64", "yuan", nullable=True),
        "fv_value_chg_gain": FieldSpec("fv_value_chg_gain", "float64", "yuan", nullable=True),
        "invest_income": FieldSpec("invest_income", "float64", "yuan", nullable=True),
        "ass_invest_income": FieldSpec("ass_invest_income", "float64", "yuan", nullable=True),
        "forex_gain": FieldSpec("forex_gain", "float64", "yuan", nullable=True),
        "total_cogs": FieldSpec("total_cogs", "float64", "yuan", nullable=True,
                                description="营业总成本"),
        "oper_cost": FieldSpec("oper_cost", "float64", "yuan", nullable=True),
        "int_exp": FieldSpec("int_exp", "float64", "yuan", nullable=True),
        "comm_exp": FieldSpec("comm_exp", "float64", "yuan", nullable=True),
        "biz_tax_surchg": FieldSpec("biz_tax_surchg", "float64", "yuan", nullable=True),
        "sell_exp": FieldSpec("sell_exp", "float64", "yuan", nullable=True),
        "admin_exp": FieldSpec("admin_exp", "float64", "yuan", nullable=True),
        "fin_exp": FieldSpec("fin_exp", "float64", "yuan", nullable=True),
        "assets_impair_loss": FieldSpec("assets_impair_loss", "float64", "yuan", nullable=True),
        "prem_refund": FieldSpec("prem_refund", "float64", "yuan", nullable=True),
        "compens_payout": FieldSpec("compens_payout", "float64", "yuan", nullable=True),
        "reser_insur_liab": FieldSpec("reser_insur_liab", "float64", "yuan", nullable=True),
        "div_pmt": FieldSpec("div_pmt", "float64", "yuan", nullable=True),
        "reins_exp": FieldSpec("reins_exp", "float64", "yuan", nullable=True),
        "oper_exp": FieldSpec("oper_exp", "float64", "yuan", nullable=True),
        "compens_payout_refu": FieldSpec("compens_payout_refu", "float64", "yuan", nullable=True),
        "insur_reser_refu": FieldSpec("insur_reser_refu", "float64", "yuan", nullable=True),
        "reins_cost_refund": FieldSpec("reins_cost_refund", "float64", "yuan", nullable=True),
        "other_costs": FieldSpec("other_costs", "float64", "yuan", nullable=True),
        "operate_profit": FieldSpec("operate_profit", "float64", "yuan", nullable=True,
                                    description="营业利润"),
        "non_oper_income": FieldSpec("non_oper_income", "float64", "yuan", nullable=True),
        "non_oper_exp": FieldSpec("non_oper_exp", "float64", "yuan", nullable=True),
        "nca_disploss": FieldSpec("nca_disploss", "float64", "yuan", nullable=True),
        "total_profit": FieldSpec("total_profit", "float64", "yuan", nullable=True,
                                  description="利润总额"),
        "income_tax": FieldSpec("income_tax", "float64", "yuan", nullable=True),
        "n_income": FieldSpec("n_income", "float64", "yuan", nullable=True,
                              description="净利润"),
        "n_income_attr_p": FieldSpec("n_income_attr_p", "float64", "yuan", nullable=True,
                                     description="归母净利润"),
        "minority_gain": FieldSpec("minority_gain", "float64", "yuan", nullable=True),
        "oth_compr_income": FieldSpec("oth_compr_income", "float64", "yuan", nullable=True),
        "t_compr_income": FieldSpec("t_compr_income", "float64", "yuan", nullable=True),
        "compr_inc_attr_p": FieldSpec("compr_inc_attr_p", "float64", "yuan", nullable=True),
        "compr_inc_attr_m": FieldSpec("compr_inc_attr_m", "float64", "yuan", nullable=True),
        "ebit": FieldSpec("ebit", "float64", "yuan", nullable=True),
        "ebitda": FieldSpec("ebitda", "float64", "yuan", nullable=True),
        "insurance_exp": FieldSpec("insurance_exp", "float64", "yuan", nullable=True),
        "undist_profit": FieldSpec("undist_profit", "float64", "yuan", nullable=True),
        "distable_profit": FieldSpec("distable_profit", "float64", "yuan", nullable=True),
        "rd_exp": FieldSpec("rd_exp", "float64", "yuan", nullable=True),
        "fin_exp_int_exp": FieldSpec("fin_exp_int_exp", "float64", "yuan", nullable=True),
        "fin_exp_int_inc": FieldSpec("fin_exp_int_inc", "float64", "yuan", nullable=True),
        "transfer_surplus_rese": FieldSpec("transfer_surplus_rese", "float64", "yuan", nullable=True),
        "transfer_housing_imprest": FieldSpec("transfer_housing_imprest", "float64", "yuan", nullable=True),
        "transfer_oth": FieldSpec("transfer_oth", "float64", "yuan", nullable=True),
        "adj_lossgain": FieldSpec("adj_lossgain", "float64", "yuan", nullable=True),
        "withdra_legal_surplus": FieldSpec("withdra_legal_surplus", "float64", "yuan", nullable=True),
        "withdra_legal_publicfund": FieldSpec("withdra_legal_publicfund", "float64", "yuan", nullable=True),
        "withdra_biz_devfund": FieldSpec("withdra_biz_devfund", "float64", "yuan", nullable=True),
        "withdra_rese_fund": FieldSpec("withdra_rese_fund", "float64", "yuan", nullable=True),
        "withdra_oth_ersu": FieldSpec("withdra_oth_ersu", "float64", "yuan", nullable=True),
        "workers_welfare": FieldSpec("workers_welfare", "float64", "yuan", nullable=True),
        "distr_profit_shrhder": FieldSpec("distr_profit_shrhder", "float64", "yuan", nullable=True),
        "prfshare_payable_dvd": FieldSpec("prfshare_payable_dvd", "float64", "yuan", nullable=True),
        "comshare_payable_dvd": FieldSpec("comshare_payable_dvd", "float64", "yuan", nullable=True),
        "capit_comstock_div": FieldSpec("capit_comstock_div", "float64", "yuan", nullable=True),
        "update_flag": FieldSpec("update_flag", "string", "flag", nullable=True),
    },
    source_mapping={
        "tushare": {f: f for f in [
            "ts_code", "ann_date", "f_ann_date", "end_date", "report_type",
            "basic_eps", "diluted_eps", "total_revenue", "revenue",
            "int_income", "prem_earned", "comm_income", "n_commis_income",
            "n_oth_income", "n_oth_b_income", "prem_income", "out_prem",
            "une_prem_reser", "reins_income", "n_sec_tb_income", "n_sec_uw_income",
            "n_asset_mg_income", "oth_b_income", "fv_value_chg_gain",
            "invest_income", "ass_invest_income", "forex_gain", "total_cogs",
            "oper_cost", "int_exp", "comm_exp", "biz_tax_surchg",
            "sell_exp", "admin_exp", "fin_exp", "assets_impair_loss",
            "prem_refund", "compens_payout", "reser_insur_liab", "div_pmt",
            "reins_exp", "oper_exp", "compens_payout_refu", "insur_reser_refu",
            "reins_cost_refund", "other_costs", "operate_profit",
            "non_oper_income", "non_oper_exp", "nca_disploss", "total_profit",
            "income_tax", "n_income", "n_income_attr_p", "minority_gain",
            "oth_compr_income", "t_compr_income", "compr_inc_attr_p",
            "compr_inc_attr_m", "ebit", "ebitda", "insurance_exp",
            "undist_profit", "distable_profit", "rd_exp", "fin_exp_int_exp",
            "fin_exp_int_inc", "transfer_surplus_rese", "transfer_housing_imprest",
            "transfer_oth", "adj_lossgain", "withdra_legal_surplus",
            "withdra_legal_publicfund", "withdra_biz_devfund", "withdra_rese_fund",
            "withdra_oth_ersu", "workers_welfare", "distr_profit_shrhder",
            "prfshare_payable_dvd", "comshare_payable_dvd", "capit_comstock_div",
            "update_flag",
        ]},
    },
)
